extend = [
    { path = "target/cargo-make/Makefile.toml" },
]

[config]
load_script = """[ -d "./target/cargo-make" ] || git clone https://github.com/rust-wiiu/Makefile.git ./target/cargo-make"""

[tasks.build]
clear = true
# dependencies = ["kernel", "wuhb"]
dependencies = ["wuhb"]

[tasks.run]
clear = true
command = "../cemu/Cemu"
args = ["-g", "${OUT_FILE}"]
dependencies = ["build"]

[tasks.upload]
env = { IP = "10.0.0.69", TO = "fs/vol/external01/wiiu/apps/test/${CARGO_MAKE_PROJECT_NAME}.wuhb" }
command = "curl"
args = ["-s", "-m", "5", "-T", "${OUT_FILE}", "ftp://${IP}/${TO}"]
dependencies = ["build"]
